openapi: 3.0.3

info:
  title: Lekhai API
  description: API specification for Lekhai backend services
  version: {{VERSION}}

servers:
  - url: http://localhost:8080
    description: Local dev server
  - url: https://lekhai.sitswiftcloud.in
    description: UAT server

tags:
  - name: Lekhai
    description: Lekhai APIs

paths:
  $ref: ./paths.yaml

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []